server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bjs?useUnicode=true&characterEncoding=utf8
    username: root
    password: Aa123456

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password: Aa123456
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 3000


mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.upoint.domain
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*/*.xml


logging:
  level:
    com:
      upoint:
        mapper: debug


